AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

inherit_gem:
  rubocop-ronin: rubocop.yml

#
# ronin-wordlists specific exceptions
#

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lint/{**/}*.rb'

# make an exception for when we need to test the #each method directly
Style/MapIntoArray:
  Exclude:
    - 'spec/cache_dir_spec.rb'
    - 'spec/search_paths_spec.rb'
    - 'spec/wordlist_dir_spec.rb'
